### ISSUE TITLE
Publish on Nexus

### ISSUE THREAD

**Issue by frassinier** [Talend/bootstrap-theme#12]
In order to install this project with npm install command, we need to publish on Talend Nexus.
For now, the best workaround is to install it from Github with `npm i -S Talend/bootstrap-theme`.

**Comment by jmfrancois** [comment]
Why on nexus ? this is not a private repository, should be published on npm

**Comment by acateland** [comment]
its not private repos but isn't intended for external use at all.

**Comment by talend-sromain** [comment]
If an talend open source project use it, i think it should be in npm in order to have the open source project work for externals contributors.
What is your opinion about the location of this library ?

**Comment by frassinier** [comment]
I think the real matter is will it be used by projects outside Talend or not (and I guess not).
So publishing it on Nexus on the public side is a good answer.

**Comment by frassinier** [comment]
I close this issue since our first version is on NPM.
