### ISSUE TITLE
Master must be a protrected branch

### ISSUE THREAD

**Issue by frassinier** [Talend/bootstrap-theme#25]
I suggest this kind of configuration

![protected branch master](https://cloud.githubusercontent.com/assets/18534166/18587716/a3b8f71a-7c23-11e6-925f-c58dee5f5f6e.png)

@Talend/frontend What do think about it?

**Comment by talend-glorieux** [comment]
I like it but I would also include the administrators just to make sure every piece of code gets reviewed.

**Comment by frassinier** [comment]
Sure, you are right!

**Comment by frassinier** [comment]
Ok, done.

![protected branch master](https://cloud.githubusercontent.com/assets/18534166/18669882/6a162858-7f3d-11e6-9a05-622f87cd6067.png)
