### ISSUE TITLE
sass-lint reports 183 problems (20 errors, 163 warnings)

### ISSUE THREAD

**Issue by jmfrancois** [Talend/bootstrap-theme#39]
First we have a sass-lint configuration but I didn't find any way to lint on my local install.
I will PR for that.

Next indentation decided was tabs, here it seems it was 4 spaces (I will PR on that too)

Next I have run the linter and here it is.
At the moment we don't have codacy report on PR but we will.
So we should care about this.

Could we be agreed on it before fixing it ?

src/theme/_breadcrumbs.scss
  19:5   warning  Expected indentation of 1 space but found 4    indentation
  20:5   warning  Expected indentation of 1 space but found 4    indentation
  21:5   warning  Expected indentation of 1 space but found 4    indentation
  22:5   warning  Expected indentation of 1 space but found 4    indentation
  24:5   warning  Expected indentation of 1 space but found 4    indentation
  25:9   warning  Expected indentation of 2 spaces but found 8   indentation
  27:9   warning  Expected indentation of 2 spaces but found 8   indentation
  28:9   warning  Expected indentation of 2 spaces but found 8   indentation
  29:9   warning  Expected indentation of 2 spaces but found 8   indentation
  30:9   warning  Expected indentation of 2 spaces but found 8   indentation
  31:13  warning  Expected indentation of 3 spaces but found 12  indentation
  32:13  warning  Expected indentation of 3 spaces but found 12  indentation
  36:5   warning  Expected indentation of 1 space but found 4    indentation
  37:9   warning  Expected indentation of 2 spaces but found 8   indentation
  38:9   warning  Expected indentation of 2 spaces but found 8   indentation
  40:9   warning  Expected indentation of 2 spaces but found 8   indentation
  41:13  warning  Expected indentation of 3 spaces but found 12  indentation
  42:13  warning  Expected indentation of 3 spaces but found 12  indentation
  44:13  warning  Expected indentation of 3 spaces but found 12  indentation
  45:17  warning  Expected indentation of 4 spaces but found 16  indentation
  46:17  warning  Expected indentation of 4 spaces but found 16  indentation
  47:17  warning  Expected indentation of 4 spaces but found 16  indentation
  48:17  warning  Expected indentation of 4 spaces but found 16  indentation
  49:17  warning  Expected indentation of 4 spaces but found 16  indentation
  50:17  warning  Expected indentation of 4 spaces but found 16  indentation
  51:17  warning  Expected indentation of 4 spaces but found 16  indentation
  52:17  warning  Expected indentation of 4 spaces but found 16  indentation
  53:17  warning  Expected indentation of 4 spaces but found 16  indentation
  54:17  warning  Expected indentation of 4 spaces but found 16  indentation
  55:17  warning  Expected indentation of 4 spaces but found 16  indentation
  56:17  warning  Expected indentation of 4 spaces but found 16  indentation
  60:9   warning  Expected indentation of 2 spaces but found 8   indentation
  61:9   warning  Expected indentation of 2 spaces but found 8   indentation
  62:13  warning  Expected indentation of 3 spaces but found 12  indentation
  63:17  warning  Expected indentation of 4 spaces but found 16  indentation
  64:17  warning  Expected indentation of 4 spaces but found 16  indentation
  65:17  warning  Expected indentation of 4 spaces but found 16  indentation
  66:17  warning  Expected indentation of 4 spaces but found 16  indentation
  67:17  warning  Expected indentation of 4 spaces but found 16  indentation
  68:17  warning  Expected indentation of 4 spaces but found 16  indentation
  69:17  warning  Expected indentation of 4 spaces but found 16  indentation
  70:17  warning  Expected indentation of 4 spaces but found 16  indentation

src/theme/_buttons.scss
  23:3   warning  Expected indentation of 1 space but found 2         indentation
  23:17  warning  Space expected around operator                      space-around-operator
  23:19  warning  Space expected around operator                      space-around-operator
  27:3   warning  Expected indentation of 1 space but found 2         indentation
  28:3   warning  Expected indentation of 1 space but found 2         indentation
  29:3   warning  Expected indentation of 1 space but found 2         indentation
  29:18  error    Include leading zeros on numbers                    leading-zero
  30:3   warning  Expected indentation of 1 space but found 2         indentation
  32:3   warning  Expected indentation of 1 space but found 2         indentation
  33:3   warning  Expected indentation of 1 space but found 2         indentation
  34:3   warning  Expected indentation of 1 space but found 2         indentation
  35:3   warning  Expected indentation of 1 space but found 2         indentation
  36:3   warning  Expected indentation of 1 space but found 2         indentation
  37:5   warning  Expected indentation of 2 spaces but found 4        indentation
  37:13  error    A value of `0` is not allowed. `none` must be used  border-zero
  40:3   warning  Expected indentation of 1 space but found 2         indentation
  41:5   warning  Expected indentation of 2 spaces but found 4        indentation
  44:3   warning  Expected indentation of 1 space but found 2         indentation
  45:5   warning  Expected indentation of 2 spaces but found 4        indentation
  48:3   warning  Expected indentation of 1 space but found 2         indentation
  49:5   warning  Expected indentation of 2 spaces but found 4        indentation
  52:3   warning  Expected indentation of 1 space but found 2         indentation
  53:5   warning  Expected indentation of 2 spaces but found 4        indentation
  56:3   warning  Expected indentation of 1 space but found 2         indentation
  57:5   warning  Expected indentation of 2 spaces but found 4        indentation
  60:3   warning  Expected indentation of 1 space but found 2         indentation
  61:5   warning  Expected indentation of 2 spaces but found 4        indentation

src/theme/_colors.scss
  40:17  error  Hex values should use the shorthand format - 3 characters where possible  hex-length
  45:17  error  Hex values should use the shorthand format - 3 characters where possible  hex-length

src/theme/_forms.scss
  7:5  warning  Expected indentation of 1 space but found 4   indentation
  8:9  warning  Expected indentation of 2 spaces but found 8  indentation

src/theme/_helpers.scss
   8:3  warning  Expected indentation of 1 space but found 2  indentation
  18:3  warning  Expected indentation of 1 space but found 2  indentation

src/theme/_navbar.scss
  11:5   warning  Expected indentation of 1 space but found 4    indentation
  12:5   warning  Expected indentation of 1 space but found 4    indentation
  13:9   warning  Expected indentation of 2 spaces but found 8   indentation
  14:13  warning  Expected indentation of 3 spaces but found 12  indentation
  15:13  warning  Expected indentation of 3 spaces but found 12  indentation
  15:28  error    Include leading zeros on numbers               leading-zero
  16:13  warning  Expected indentation of 3 spaces but found 12  indentation
  18:13  warning  Expected indentation of 3 spaces but found 12  indentation
  19:17  warning  Expected indentation of 4 spaces but found 16  indentation
  20:17  warning  Expected indentation of 4 spaces but found 16  indentation
  21:17  warning  Expected indentation of 4 spaces but found 16  indentation
  22:17  warning  Expected indentation of 4 spaces but found 16  indentation
  23:17  warning  Expected indentation of 4 spaces but found 16  indentation
  24:17  warning  Expected indentation of 4 spaces but found 16  indentation

src/theme/_variables.scss
   36:25  warning  Hex notation should all be upper case                           hex-notation
   53:36  error    Strings must use single quotes                                  quotes
   89:51  error    Strings must use single quotes                                  quotes
   89:65  error    Strings must use single quotes                                  quotes
   92:27  error    Strings must use single quotes                                  quotes
   94:27  error    Strings must use single quotes                                  quotes
  121:29  warning  Hex notation should all be upper case                           hex-notation
  143:33  warning  Hex notation should all be upper case                           hex-notation
  145:33  warning  Hex notation should all be upper case                           hex-notation
  149:33  warning  Hex notation should all be upper case                           hex-notation
  159:34  warning  Hex notation should all be upper case                           hex-notation
  160:34  warning  Hex notation should all be upper case                           hex-notation
  162:34  warning  Hex notation should all be upper case                           hex-notation
  166:34  warning  Hex notation should all be upper case                           hex-notation
  170:34  warning  Hex notation should all be upper case                           hex-notation
  174:34  warning  Hex notation should all be upper case                           hex-notation
  178:34  warning  Hex notation should all be upper case                           hex-notation
  195:34  warning  Hex notation should all be upper case                           hex-notation
  202:34  warning  Hex notation should all be upper case                           hex-notation
  214:34  warning  Hex notation should all be upper case                           hex-notation
  230:34  warning  Hex notation should all be upper case                           hex-notation
  246:34  warning  Hex notation should all be upper case                           hex-notation
  248:40  warning  Commas should be followed by a space                            space-after-comma
  248:42  warning  Commas should be followed by a space                            space-after-comma
  248:44  warning  Commas should be followed by a space                            space-after-comma
  248:44  error    Include leading zeros on numbers                                leading-zero
  250:34  warning  Hex notation should all be upper case                           hex-notation
  252:34  warning  Hex notation should all be upper case                           hex-notation
  259:34  warning  Hex notation should all be upper case                           hex-notation
  387:57  error    Include leading zeros on numbers                                leading-zero
  397:44  warning  Hex notation should all be upper case                           hex-notation
  399:44  warning  Hex notation should all be upper case                           hex-notation
  419:45  warning  Hex notation should all be upper case                           hex-notation
  424:45  warning  Hex notation should all be upper case                           hex-notation
  440:45  warning  Hex notation should all be upper case                           hex-notation
  446:45  warning  Hex notation should all be upper case                           hex-notation
  448:51  warning  Hex notation should all be upper case                           hex-notation
  462:40  warning  Hex notation should all be upper case                           hex-notation
  463:40  warning  Hex notation should all be upper case                           hex-notation
  467:40  warning  Hex notation should all be upper case                           hex-notation
  469:40  warning  Hex notation should all be upper case                           hex-notation
  474:40  warning  Hex notation should all be upper case                           hex-notation
  475:40  warning  Hex notation should all be upper case                           hex-notation
  534:31  warning  Hex notation should all be upper case                           hex-notation
  537:30  error    Include leading zeros on numbers                                leading-zero
  550:39  warning  Hex notation should all be upper case                           hex-notation
  554:45  warning  Commas should be followed by a space                            space-after-comma
  554:47  warning  Commas should be followed by a space                            space-after-comma
  554:49  error    Include leading zeros on numbers                                leading-zero
  554:49  warning  Commas should be followed by a space                            space-after-comma
  556:39  warning  Hex notation should all be upper case                           hex-notation
  569:39  error    Function 'fade_in' should be written in lowercase with hyphens  function-name-format
  592:31  warning  Hex notation should all be upper case                           hex-notation
  594:31  warning  Hex notation should all be upper case                           hex-notation
  610:48  warning  Hex notation should all be upper case                           hex-notation
  612:54  warning  Commas should be followed by a space                            space-after-comma
  612:56  warning  Commas should be followed by a space                            space-after-comma
  612:58  error    Include leading zeros on numbers                                leading-zero
  612:58  warning  Commas should be followed by a space                            space-after-comma
  619:30  error    Include leading zeros on numbers                                leading-zero
  621:31  warning  Hex notation should all be upper case                           hex-notation
  660:31  warning  Hex notation should all be upper case                           hex-notation
  662:31  warning  Hex notation should all be upper case                           hex-notation
  683:33  warning  Hex notation should all be upper case                           hex-notation
  685:33  warning  Hex notation should all be upper case                           hex-notation
  690:33  warning  Hex notation should all be upper case                           hex-notation
  716:31  warning  Hex notation should all be upper case                           hex-notation
  723:31  warning  Hex notation should all be upper case                           hex-notation
  724:31  warning  Hex notation should all be upper case                           hex-notation
  727:31  warning  Hex notation should all be upper case                           hex-notation
  728:31  warning  Hex notation should all be upper case                           hex-notation
  730:31  warning  Hex notation should all be upper case                           hex-notation
  759:31  warning  Hex notation should all be upper case                           hex-notation
  773:31  warning  Hex notation should all be upper case                           hex-notation
  781:31  warning  Hex notation should all be upper case                           hex-notation
  783:31  warning  Hex notation should all be upper case                           hex-notation
  789:31  warning  Hex notation should all be upper case                           hex-notation
  803:33  warning  Hex notation should all be upper case                           hex-notation
  809:33  error    Strings must use single quotes                                  quotes
  816:63  warning  Commas should be followed by a space                            space-after-comma
  816:65  warning  Commas should be followed by a space                            space-after-comma
  816:67  warning  Commas should be followed by a space                            space-after-comma
  816:67  error    Include leading zeros on numbers                                leading-zero
  818:47  warning  Hex notation should all be upper case                           hex-notation
  820:46  error    Include leading zeros on numbers                                leading-zero
  823:47  warning  Hex notation should all be upper case                           hex-notation
  824:47  warning  Hex notation should all be upper case                           hex-notation
  826:47  warning  Hex notation should all be upper case                           hex-notation
  835:39  warning  Hex notation should all be upper case                           hex-notation
  842:31  warning  Hex notation should all be upper case                           hex-notation
  843:31  warning  Hex notation should all be upper case                           hex-notation
  845:31  warning  Hex notation should all be upper case                           hex-notation
  848:31  warning  Hex notation should all be upper case                           hex-notation
  850:31  warning  Hex notation should all be upper case                           hex-notation

✖ 183 problems (20 errors, 163 warnings)

**Comment by frassinier** [comment]
@jmfrancois Please, which tool do you use?

**Comment by jmfrancois** [comment]
I'm using [sass-lint](https://www.npmjs.com/package/sass-lint) with the provided default config from tools repository

**Comment by frassinier** [comment]
It was fixed by https://github.com/Talend/bootstrap-theme/pull/43
