### ISSUE TITLE
button hover

### ISSUE THREAD

**Issue by acateland** [Talend/bootstrap-theme#56]
'btn' css class has a hover state that set a background color, even if it is used with 'btn-link', wich is weird when used on top of a bacground of color.

**Comment by frassinier** [comment]
Do you have any example?

If a button is on top of a container with a dark background, then it must have a specific style like inside header navbar or aside nav. 

It is not a theme issue I guess?

**Comment by frassinier** [comment]
Ok, I get it! I will fix it ASAP.

![2016-10-18 09-03](https://cloud.githubusercontent.com/assets/18534166/19467505/d5d5dcb6-9511-11e6-858c-23aaf2478b74.gif)
