### ISSUE TITLE
Create a GitHub page with examples and documentation

### ISSUE THREAD

**Issue by talend-glorieux** [Talend/bootstrap-theme#7]
Adding a GitHub page containing live example of components would make it easier for developers and designers to mockup, test and improve the components.

Adding the [generated sass-doc](http://sassdoc.com/) could also be a good thing.

**Comment by frassinier** [comment]
I like the way how Pivotal expose[ its guideline](http://styleguide.cfapps.io/) with two distinct parts, React components and UI ones.

**Comment by frassinier** [comment]
We can also use [Frontify](https://app.frontify.com/d/xawdeLsCK7Vn/talend-style-guide) to propulse a UI demo.

**Comment by frassinier** [comment]
At first, I proprose to link gh-pages to sassdoc generated static doc.  
We will need to trigger manually its generation before commit.

**Comment by talend-glorieux** [comment]
The goal is to have the CI do it for us. I really don't want to have to think about generating the documentation every time someone pushes.
