### ISSUE TITLE
buttons without label

### ISSUE THREAD

**Issue by acateland** [Talend/bootstrap-theme#85]
When defining a button group, without label but an sag icon, if one element of this group is disabled the height of this element is inferior.

![capture d ecran 2016-11-30 a 11 07 57 2](https://cloud.githubusercontent.com/assets/19344650/20748144/566601b0-b6ed-11e6-84e3-c36519204b89.png)

**Comment by jmfrancois** [comment]
You mean the icon height change the btn height ?

**Comment by frassinier** [comment]
Looks good to me.

![react storybook](https://cloud.githubusercontent.com/assets/18534166/22015900/4ec2e842-dca4-11e6-9257-577653fd7187.png)
